# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mi_mensaje.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mi_mensaje.proto',
  package='pb',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x10mi_mensaje.proto\x12\x02pb\"7\n\nmi_mensaje\x12\x0f\n\x07\x63omment\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\x12\x0c\n\x04\x64\x61te\x18\x03 \x01(\x05\x62\x06proto3'
)




_MI_MENSAJE = _descriptor.Descriptor(
  name='mi_mensaje',
  full_name='pb.mi_mensaje',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='comment', full_name='pb.mi_mensaje.comment', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='pb.mi_mensaje.id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='date', full_name='pb.mi_mensaje.date', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=79,
)

DESCRIPTOR.message_types_by_name['mi_mensaje'] = _MI_MENSAJE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

mi_mensaje = _reflection.GeneratedProtocolMessageType('mi_mensaje', (_message.Message,), {
  'DESCRIPTOR' : _MI_MENSAJE,
  '__module__' : 'mi_mensaje_pb2'
  # @@protoc_insertion_point(class_scope:pb.mi_mensaje)
  })
_sym_db.RegisterMessage(mi_mensaje)


# @@protoc_insertion_point(module_scope)
